Remove prettier check and update blog rss feed

diff --git a/.github/workflows/prettier-html.yml b/.github/workflows/prettier-html.yml
--- a/.github/workflows/prettier-html.yml
+++ b/.github/workflows/prettier-html.yml
@@ -18,14 +18,14 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v4
 
-      - name: Install Prettier
-        run: npm install -g prettier
+      # - name: Install Prettier
+      #   run: npm install -g prettier
 
-      - name: Check for Prettier
-        run: npx prettier --version || echo "Prettier not found"
+      # - name: Check for Prettier
+      #   run: npx prettier --version || echo "Prettier not found"
 
-      - name: Run Prettier on HTML files
-        run: npx prettier --write '**/*.html'
+      # - name: Run Prettier on HTML files
+      #   run: npx prettier --write '**/*.html'
 
       - name: Commit and push changes
         run: |
